---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: binx-os
description: Custom Wayblue Hyprland workstation image.
base-image: ghcr.io/wayblueorg/hyprland-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - atim/lazygit
    install:
      packages:
        - starship
        - fish
        - neovim
        - stow
        - ripgrep
        - fd-find
        - lazygit
        - tmux
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - dev.zed.Zed
          - com.github.tchx84.Flatseal
      - scope: user

  - type: signing
